### ISSUE TITLE
Pre-launch: add production Stripe/PayPal creds

### ISSUE THREAD

**Issue by fmann** [creativecommons/new-creativecommons.org#1]
For Stripe, go to:

Forms > Stripe 

For PayPal, go to:

Forms > Forms > Donate > Settings > PayPal > and in each feed change the PayPal email address to the production payment email.

**Comment by robinpuga** [comment]
Please let us know when we can test the production credentials in Stripe / Paypal.

**Comment by mattl** [comment]
PayPal is done, but I don't see the Stripe form you're talking about.

**Comment by ageeroms** [comment]
https://staging.creativecommons.org/wordpress/wp-admin/admin.php?page=gf_settings&subview=gravityformsstripe
needs credentials.

Thanks,
Anna

On Tue, Jun 21, 2016 at 12:22 PM, Matt Lee <notifications@github.com> wrote:

> PayPal is done, but I don't see the Stripe form you're talking about.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/new-creativecommons.org/issues/1#issuecomment-227544163>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDiXB2R7OCDU9SbkMhv_zK4hxthfcks5qODndgaJpZM4I1u8Q>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7

**Comment by mattl** [comment]
Okay, all set.
