### ISSUE TITLE
Where does the newsletter signup data go?

### ISSUE THREAD

**Issue by mattl** [creativecommons/new-creativecommons.org#11]

**Comment by mattl** [comment]
The Mailchimp stuff has been resolved now, and we're staying with Civi.

**Comment by little-wow** [comment]
I jus tested this, and this is the email I got.  Is there a reason why I am getting an email every time someone signs up for the email list?  Is there any way to turn that off?

<img width="824" alt="screen shot 2016-06-21 at 1 47 48 pm" src="https://cloud.githubusercontent.com/assets/7093838/16245677/d64ee45c-37b6-11e6-820d-be60e0f98a21.png">

**Comment by mattl** [comment]
I turned it off to avoid killing your inbox.
