### ISSUE TITLE
Fix static links in spreadsheet

### ISSUE THREAD

**Issue by little-wow** [creativecommons/new-creativecommons.org#12]
https://docs.google.com/spreadsheets/d/1kZouwYEGcYL74mRcuJWBvgt_1iKKnm1PVG5Fa8mhgrM/edit#gid=0

**Comment by ageeroms** [comment]
@little-wow , could you please let me know what you mean about fixing static links? 

For background, there is a very large number of existing redirects that Matt/Rob have configured. The redirects spreadsheet only represents changes that I needed based on content adjusts I did. Now that Rob/Matt have added the production redirects, there may be some oddities that need to be corrected. For example, Robin noticed that if a URL contained the word technology, it was being redirected to the wiki--hence that broken technology image, so he ticketed that. If you notice oddities like that, please ticket here for Matt.

**Comment by mattl** [comment]
Resolving this.
