### ISSUE TITLE
FAQ redirect

### ISSUE THREAD

**Issue by little-wow** [creativecommons/new-creativecommons.org#14]
When we received the staging site for review, /faq redirected to http://creativecommons.org/faq/ with the TOC and the old skin.

I created staging.creativecommons.org/faq because I thought this looked bad, but didn't realize that the FAQ was in multiple languages. 
Can we make staging.cc.org/faq resolve to the correct FAQ but with the new skin?

**Comment by ageeroms** [comment]
I think Matt has plans to skin that old FAQ, so appearance should be better.

Please confirm @mattl  and ensure /faq resolves to the static FAQ with new template.

**Comment by mattl** [comment]
Yeah /faq is going to the static page.

**Comment by ageeroms** [comment]
@mattl , thanks for that. Also, the breadcrumb should be updated from Page Title to FAQ. Also, I don't see a way to get to the French version from https://staging.creativecommons.org/faq/ .
