### ISSUE TITLE
New photos for board

### ISSUE THREAD

**Issue by little-wow** [creativecommons/new-creativecommons.org#15]
The photos of the board are really low-res and look bad. We need new photos of these people. 

Also the responsiveness of this section leaves certain team and board members hanging out alone at the bottom of the list of people on the screen. If we add anyone to this list, then they will be lonely. See attached screenshot for an example of both these issues.

<img width="970" alt="screen shot 2016-06-21 at 11 49 55 am" src="https://cloud.githubusercontent.com/assets/7093838/16242229/5859ecd2-37a6-11e6-9356-204ad318d858.png">

**Comment by ageeroms** [comment]
Hi Jennie,

Yes, ideally you would upload higher resolution photos of your board members, as I outlined in our meeting regarding content entry. You mentioned that you might request new ones. I suggested that downloading the photo currently on your website and using Google Image Search to find a higher resolution option was likely a less time-consuming option, as it's hard to get folks to respond quickly to provide updated photos.

Also, if you wish to omit board members from that page and simply create a static page like your existing production board page for launch, as a temporary solution, that is an option--so let me know if you need help with that.

If you would like us to help you finish content entry in that section, we have folks on staff who could assist and we can invoice separately for this.

I see what you mean about Molly looking lonely, but this is unavoidable with this type of design, which was requested by CC. Also, this type of design is being used extensively and I think users are becoming more accepting of the constraints.

**Comment by little-wow** [comment]
Content entry is finished, and the main issue is the low-res images.
