### ISSUE TITLE
Google Analytics event tracking

### ISSUE THREAD

**Issue by little-wow** [creativecommons/new-creativecommons.org#16]
@ageeroms has asked for these events only to be tracked:
* click donate button in header
* click donate in footer
* complete donation via form on donate page
* sign up for newsletter on homepage 
* sign up for newsletter in sidebar inside page

I *think* we currently have a lot more GA events on the CC page, and I would like to be able to track user flow in addition to knowing who donated.  I can begin by adding GA to these events as per Anna's screenshot, but I'd like more info on where GA is/will be added, etc, etc. I feel like I was brought in late to this and possibly don't understand how we're going to be using GA for this page.

**Comment by mattl** [comment]
Renamed it as we have another GA issue open. I don't know how we'd do this... but I'm going to add the plugin requested by @creativecommons/affinity-bridge

**Comment by ericsteuer** [comment]
over my head, sorry. unsubscribing.

**Comment by ageeroms** [comment]
@little-wow , per my email here are the instructions for configuring the event tracking on forms: 
----------------

Once this plugin is activated, you can browse to the Gravity Forms settings and find a new sub-menu item called Event Tracker. There, you will enter your Google Analytics Tracking Code.

The plugin provides some default event categories, labels, and actions. You can override these per form by going into the individual form's settings.

Within Google Analytics, you will want to set up an event-based goal and match the event label, event category, and event action with the ones you set up.

On each form, you need to make sure to setup an Event Tracking Feed. Open each forms settings, go to the "Event Tracking" section, and set one up. Leave the fields blank to use the default values.

------------

Please let us know how we can help.

**Comment by little-wow** [comment]
@mattl @ageeroms I don't have a high enough admin privilege to access gravity forms

**Comment by mattl** [comment]
I'll take care of this

**Comment by mattl** [comment]
Moving this to postlaunch
