### ISSUE TITLE
Plugins installed on the site don't match the composer file

### ISSUE THREAD

**Issue by mattl** [creativecommons/new-creativecommons.org#17]
https://github.com/creativecommons/new-creativecommons.org/edit/master/composer.json

Can we get that file updated with all the plugins we need for launch?

**Comment by fmann** [comment]
I think everything from staging is in there. @mattl What is missing? Recall that gravityforms can't be pulled in with packagist.

I went ahead and updated it with the latest updates to jetpack, wordpress-seo, and google analytics.

**Comment by mattl** [comment]
Ah, I was looking for Yoast but I guess that's wordpress-seo under the hood. Okay, thanks.
