### ISSUE TITLE
New site leaks everyone's email addresses?

### ISSUE THREAD

**Issue by mattl** [creativecommons/new-creativecommons.org#19]
![screenshot from 2016-06-21 15-14-25](https://cloud.githubusercontent.com/assets/33296/16244703/e966f8de-37c2-11e6-9f4c-af215a5da2c2.png)

**Comment by mattl** [comment]
Also in the URL, kinda...

**Comment by ageeroms** [comment]
This is correctable re breadcrumb by updating the user's display name. I
fixed Scott and a few others.

it shows in path for users that have email=username, which isn't really a
security best practice. Our dev checking whether we can change pattern or
perhaps look at updating the username of the relevant users.

Thanks,
Anna

On Tue, Jun 21, 2016 at 1:15 PM, Matt Lee <notifications@github.com> wrote:

> Also in the URL, kinda...
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/new-creativecommons.org/issues/19#issuecomment-227558125>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDvBrsBWZ1OSZGLoBMKXsypP52qe2ks5qOEZpgaJpZM4I7IIn>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7

**Comment by mattl** [comment]
The usernames are tied to the CCID login.
