### ISSUE TITLE
Remove the phone number from the footer?

### ISSUE THREAD

**Issue by mattl** [creativecommons/new-creativecommons.org#20]
@ericsteuer we'd talked about doing this, should we go ahead and remove it ahead of the launch?

**Comment by little-wow** [comment]
Yes, there's a typo in it anyway

**Comment by ageeroms** [comment]
Strategic reason to keep was to make you seem more available and open.
Phone goes to voicemail which is emailed to Mari anyway.



On Tue, Jun 21, 2016 at 1:54 PM, Jennie Rose Halperin <
notifications@github.com> wrote:

> Yes, there's a typo in it anyway
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/new-creativecommons.org/issues/20#issuecomment-227568681>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDs3AaiF_5ci7gQOIVqdj6ETrffe5ks5qOE-JgaJpZM4I7JDt>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7

**Comment by ericsteuer** [comment]
This is a good example of an issue where I don't know who owns making the decision on it. I could say, sure, delete it, very few people use it anyway. But I don't know. And I don't believe it's my call to make.

**Comment by mattl** [comment]
Please don't call the number

**Comment by mattl** [comment]
@ageeroms If we decide to remove this later, how do we do that?

**Comment by fmann** [comment]
@mattl It is in the footer. https://github.com/creativecommons/new-www-theme/blob/master/cc/footer.php#L46

**Comment by mattl** [comment]
Thanks @fmann
