### ISSUE TITLE
Site level privileges

### ISSUE THREAD

**Issue by little-wow** [creativecommons/new-creativecommons.org#24]
I am not sure what my current privilege level is, or if I just don't know how to do things like:
edit headers and footers
gravity forms

**Comment by mattl** [comment]
What are you trying to do?

**Comment by mattl** [comment]
Gravity Forms are in the Forms panel in the admin interface, you may not be able to get there.

I'm not sure what you mean by headers and footers -- I thought you'd recently changed the header?

**Comment by little-wow** [comment]
yeah, I can't get the forms panel, and I changed the header at the site level

**Comment by mattl** [comment]
I'll do the Forms stuff

**Comment by little-wow** [comment]
You'll add the google analytics events?

**Comment by mattl** [comment]
Yep.
