### ISSUE TITLE
Removed Affinity Bridge credit from footer

### ISSUE THREAD

**Issue by mattl** [creativecommons/new-creativecommons.org#26]
We've removed the credit from the footer, it should go elsewhere on an appropriate page on the site. We have a place for vendors, etc on our services page. We'll make sure it goes there.

**Comment by mackh** [comment]
Sorry this credit was approved as part of the design and only appears on the homepage.  please reinstate it

**Comment by ryanmerkley** [comment]
Site credit in the footer was agreed to in contract by me. Mack knows the terms.

**Comment by mattl** [comment]
@peterspdx Looping you on this from https://github.com/creativecommons/creativecommons.org/issues/264

**Comment by mattl** [comment]
@mackh Have restored the link, and wrapped it in a way that'll only appear on the front page.
