### ISSUE TITLE
Spacing is off in list of platforms

### ISSUE THREAD

**Issue by little-wow** [creativecommons/new-creativecommons.org#27]
<img width="767" alt="screen shot 2016-06-21 at 9 23 08 pm" src="https://cloud.githubusercontent.com/assets/7093838/16254612/925d96e0-37f6-11e6-976a-7b6ab1e90c06.png">

The platform partners look too far to the right.

**Comment by little-wow** [comment]
sorry, I've just been looking at this too long

**Comment by ageeroms** [comment]
No, I think you're right. Something happened to indent it with last update.
I'll get our dev to address.

Thanks,
Anna

On Tue, Jun 21, 2016 at 9:26 PM, Jennie Rose Halperin <
notifications@github.com> wrote:

> sorry, I've just been looking at this too long
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/new-creativecommons.org/issues/27#issuecomment-227639868>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDrn989j6RR8sBzTLBGdTFBuzj0PDks5qOLl3gaJpZM4I7ZQP>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7
