### ISSUE TITLE
Review Civi Form Embed Styline

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/new-creativecommons.org#3]
Hey, here's the form I mentioned: https://staging.creativecommons.org/use-remix/ideas/ , which is the one that previously appeared here https://staging.creativecommons.org/use-remix/ideas/ . I think it's primarily the check-boxes being in the list items that looks unfortunate. Also, WordPress seems to want to add placeholder break tags to the text box for the comments. Probably, this just needs a bit of a run through on your side to double check that the embedded form code is indicative of what you'd be adding on an ongoing basis and then our front end dev would need to take a stab at providing a better default set of styles for these forms.

**Comment by robinpuga** [comment]
Does the new formatting for the form suffice for our needs here: https://staging.creativecommons.org/use-remix/ideas/ 

Is this form still synching properly with CiviCrm? Can someone on CC team confirm this is working as desired?

**Comment by mattl** [comment]
Yep, that looks good and works.
