### ISSUE TITLE
Site testing and bug entry

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/new-creativecommons.org#5]
https://docs.google.com/document/d/1-_dXbxxHdiwD0zB9G5ClQOU_YGLl13R-eKgx_msKT6U/edit?usp=sharing 

The above doc provides a list of simple tasks and design links with relevant links to stage.

Here's a spreadsheet for recording any items you find:

https://docs.google.com/spreadsheets/d/1-NAxjmCtPfn5kc8IvmbXinyHNv8rBvnTVtNDlTDJMOw/edit#gid=0

**Comment by mattl** [comment]
All issues are marked as will not fix or resolved
