### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by robmyers** [creativecommons/new-creativecommons.org#6]
@mattl 

obvious urls:

faq:79 GET https://staging.creativecommons.org/fonts/fontello/css/cc-fontello.css?ver=4.5.2 404 (Not Found)

toolkit:79 GET https://staging.creativecommons.org/platform/fonts/fontello/css/cc-fontello.css?ver=4.5.2 404 (Not Found)

/choose/:

(index):1 Font from origin 'https://ccstatic.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://staging.creativecommons.org' is therefore not allowed access.
(index):2404 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/fc_dubious_ho2ver.png 404 (Not Found)
(index):1 Font from origin 'https://ccstatic.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://staging.creativecommons.org' is therefore not allowed access.
(index):2411 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/chooser_cc_ho2ver.png 404 (Not Found)
(index):2412 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/chooser_by_ho2ver.png 404 (Not Found)
(index):2414 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/chooser_nc_ho2ver.png 404 (Not Found)
(index):2413 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/chooser_nd_ho2ver.png 404 (Not Found)
(index):2415 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/chooser_nc_eu_ho2ver.png 404 (Not Found)
(index):2416 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/chooser_nc_jp_ho2ver.png 404 (Not Found)
(index):2417 GET https://staging.creativecommons.org/wp-content/themes/creativecommons.org/images/hint_button_ho2ver.png 404 (Not Found)

**Comment by mattl** [comment]
Look at you with your 3 bugs in one 1 issue ;)

All broken images fixed in their repos. Please pull them... (i'll do the chooser)

**Comment by mattl** [comment]
CORS should be fixed too now.
