### ISSUE TITLE
Ligature In Affiliate Page Address

### ISSUE THREAD

**Issue by robmyers** [creativecommons/new-creativecommons.org#8]
https://staging.creativecommons.org/about/global-affiliate-network/

^ the 'ff' is a single-character ligature. To be part of a valid url it should either be percentage-encoded or, preferably, represented as two separate 'f' characters.

**Comment by ageeroms** [comment]
Updated the URL to https://staging.creativecommons.org/about/global-affiliate-network/ - good catch!

**Comment by robmyers** [comment]
Awesome.

Anyone else who checks this - your browser address line may still render the "ff" in the url as a ligature. The test is whether you can select each "f" individually or only together as a single character.
