### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/new-creativecommons.org#9]
Hey Matt and Rob,

We usually use https://wordpress.org/plugins/google-analytics-for-wordpress/ for Google Analytics (previously by Yoast). Would you like us to add that? Or do you want to take care of adding Analytics?

Thanks,
Anna

**Comment by robinpuga** [comment]
Hey Matt and Robb, did this get addressed?

**Comment by mattl** [comment]
Plugin is on disk, but doesn't appear anywhere I can see on the backend?

**Comment by ageeroms** [comment]
@fmann can you check the status of the Analytics plugin please?

**Comment by fmann** [comment]
It was in wp-content/plugins, which is where composer is building to. The actual site docroot is in docroot/wp-content/plugins. I've been wondering how you all want to address this: as a part of the build script, with a symlink, or by configuring composer. 

For this ticket, and for the time being, I've been copying the plugins over after install. It is activate-able now.

**Comment by mattl** [comment]
Oh, d'oh. We should symlink. Sorry about that.
